### ISSUE TITLE
Error compiling with ncurses installed.

### ISSUE THREAD

**Issue by finnoleary** [sabotage-linux/netbsd-curses#30]
Platform is latest Arch Linux, GCC, GNU crap, etc.
Compiling with `LDFLAGS=-static`, `PREFIX=""`.

It fails with
```
In file included from libterminfo/setupterm.c:41:0:
/usr/include/curses.h:879:32: error: conflicting types for tparam
 extern NCURSES_EXPORT(char *) tparm (NCURSES_CONST char *, ...); /*special*/

In file included from libterminfo/setupterm.c:41:0:
./libterminfo/term.h:1961:9: note: previous declaration of tparm was here
 char *  tparm(const char *, long, long, long, long, long, 
```
(Apologies if there is a typo here and there -- I had to type it out manually from a box that doesn't have internet access :( )

It seems to me as if GCC is selecting `/usr/include/curses.h` over `./curses/curses.h`, but the compile options for that module start with `-I./../curses`, so that seems unlikely.

**Comment by finnoleary** [comment]
Never mind, it compiles fine with `-I./libcurses`.

**Comment by rofl0r** [comment]
did you have to make manual changes to make it compile?

**Comment by finnoleary** [comment]
Yes. `-I./libcurses`. It disagrees with the function prototypes in my GNU libc one

**Comment by rofl0r** [comment]
ok. i guess we should add that by default then; i thought its already done...

**Comment by rofl0r** [comment]
i pushed a commit which should fix the issue, i believe. could you test it please ?
