### ISSUE TITLE
Compile fails with glibc 2.27-8

### ISSUE THREAD

**Issue by JonChesterfield** [sabotage-linux/netbsd-curses#33]
Specifically, trying to compile on standard debian box with glibc C fails in three places:

- `libcurses/refresh.c` uses `wcwidth`
- `libterminfo/term.c` uses `strlcpy`
- `libcurses/tstp.c` uses SIG_HOLD

strlcpy appears to be a BSD extension that glibc deliberately doesn't implement. The other two seem to be available under glibc (from a cursory web search) so may be missing headers.

Checked gcc 8.2 and clang 6.0 with glibc 2.27-8.

**Comment by rofl0r** [comment]
thanks for your report, i hope it works now

**Comment by JonChesterfield** [comment]
Thank you. So much for my plan to take a look at this after work :)
