### ISSUE TITLE
CANCELLED_STRING

### ISSUE THREAD

**Issue by jeremybobbin** [sabotage-linux/netbsd-curses#38]
Regarding:
`libterminfo/term_private.h:75: #define CANCELLED_STRING (char *)(-1)`

`(char *)(-1)` evaluates to `0xffffffffffff` or 16^16.

If an application calls `ti_getstr` with a bad ID string, it returns `0xffffffffffff`. Is this the intended behavior? How should an end user of this library handle this error?

Thanks

**Comment by rofl0r** [comment]
https://linux.die.net/man/3/tigetstr

> The tigetstr routine returns the value (char *)-1 if capname is not a string capability, or 0 if it is canceled or absent from the terminal description. 

appears to be the expected return value.
