### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by ericonr** [sabotage-linux/netbsd-curses#47]
Hi! I'm looking into packaging `netbsd-curses` for Void Linux, but we try to stick to proper releases from upstream instead of grabbing some git rev of a given package. Since this repo seems to have received many commits ever since the last 2019 release, I think a new release would be very helpful!

Let me know if you need help for testing anything.

**Comment by rofl0r** [comment]
have fun: https://github.com/sabotage-linux/netbsd-curses/releases/tag/v0.3.2

**Comment by ericonr** [comment]
Nice, thanks!
