### ISSUE TITLE
Issues compiling some packages

### ISSUE THREAD

**Issue by XDream8** [sabotage-linux/netbsd-curses#49]
The first package that i couldn't compile(thanks to errors) is zsh shell. (and a little note i am a gentoo user, So i am using portage to install packages)

I used this patch: http://ix.io/3uO5
Emerge build log: http://ix.io/3uO6
Emerge configure log: http://ix.io/3uO7

**Comment by rofl0r** [comment]
as you can see in your config.log:
```
configure:6239: checking for library containing tigetstr
configure:6270: x86_64-gentoo-linux-musl-gcc -o conftest -march=native -O3 -pipe  -Wl,-O1 -Wl,--as-needed conftest.c -lrt -lm  -lc >&5
/usr/lib/gcc/x86_64-gentoo-linux-musl/10.3.0/../../../../x86_64-gentoo-linux-musl/bin/ld: /var/tmp/portage/app-shells/zsh-5.8/temp/ccMDmPHD.o: in function `main':
conftest.c:(.text.startup+0x7): undefined reference to `tigetstr'
collect2: error: ld returned 1 exit status
```
neither -lcurses nor -lterminfo are in the command line.
maybe try `LIBS='-lcurses -lterminfo' ./configure` instead of that hackish patch, if that doesn't help try to override the `--with-term-lib=tinfow ncursesw` option i can see in the emerge log with `--with-term-lib='curses terminfo'`

**Comment by XDream8** [comment]
yeah that did work.

i used this environment config: (/etc/portage/env/netbsd-curses.conf) http://ix.io/3uRc
and i passed it to ebuild: (/etc/portage/package.env) http://ix.io/3uRf
then it just compiled fine

i used the same environment config but i got error while compiling procps, util-linux and alsa-utils with ncurses USE flag(they all compiled just fine when i compiled it without ncurses). the other programs like nnn compiled without problem

the most complicated one is alsa-utils i think.
Emerge build log: http://ix.io/3uRd
Emerge configure log: http://ix.io/3uRe

**Comment by rofl0r** [comment]
so everything works now? see README here, it states where to find patches for these packages.

**Comment by XDream8** [comment]
i willl thanks for the help
