### ISSUE TITLE
Provide a full generic static target

### ISSUE THREAD

**Issue by Ypnose** [sabotage-linux/netbsd-curses#5]
It could be a smart idea to provide a static-only target inside the <code>GNUMakefile</code>. The default <code>install</code> target can be easily modified with <code>sed(1)</code>, but it does not seem to be a perenial solution (for maintainers for example).  
I was thinking about something like this:
```makefile
install-static: install-headers install-stalibs install-progs install-pcs
```
This is a random (harmless) example (having a <code>all-static</code> could work too). Dunno if it's enough clean for you. I can provide a tiny patch (which is a better) if you agree with the request.

Another question: do you plan to create a tag soon?

**Comment by rofl0r** [comment]
yeah i'm fine with the proposed addition, and there's already a tag and a tarball release

**Comment by Ypnose** [comment]
Sorry about the tag, I missed it this morning.

**Comment by Ypnose** [comment]
Do you want me to provide a tiny patch or you plan to add the change by yourself?

**Comment by rofl0r** [comment]
yeah i expected that you send a PR

**Comment by rofl0r** [comment]
ok i'll go ahead and do the change myself
