### ISSUE TITLE
cross-compile with `clang`? 

### ISSUE THREAD

**Issue by hanhlinux** [sabotage-linux/netbsd-curses#50]
I see that cross-compile will be detected when `CC` is different from `HOSTCC`. So how can I work with `clang`?

**Comment by rofl0r** [comment]
just make CC different from HOSTCC. since both target different archs, they need to be different anyway.
e.g. `make CC="clang --target-arch=mips" HOSTCC="clang --target-arch=x86_64"`. replace `--target-arch` with whatever the right switch is.
